// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const colors = {
 "colorFondo": "rgba(0, 0, 0, 1)",
 "backgroundColor": "rgba(244, 236, 236, 1)",
 "panel": "rgba(0, 0, 0, 1)",
 "surfaceColor": "rgba(245, 248, 191, 1)",
 "textoBotN": "rgba(0, 0, 0, 1)",
 "textColor": "rgba(255, 255, 255, 1)",
 "colorDelBoton": "rgba(255, 255, 255, 1)",
 "buttonColor": "rgba(255, 255, 255, 1)"
} as const;

export default colors;