// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const colors = {
 "rectangle2": "rgba(243, 207, 207, 1)",
 "rectangle1": "rgba(255, 255, 255, 1)",
 "buttonColor": "rgba(255, 10, 10, 1)"
} as const;

export default colors;